name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env vars
        run: |
          echo BUILD_TIMESTAMP="$(date +%s)" >> $GITHUB_ENV
          echo REPOSITORY_NAME="$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
          echo TAG_NAME="$(echo ${{ github.ref }} | cut -d / -f3-)" >> $GITHUB_ENV
          echo SHORT_SHA="$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: server/
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.REPOSITORY_NAME }}:dev-${{ env.BUILD_TIMESTAMP }}-git.${{ env.SHORT_SHA }}
